### ISSUE TITLE
Docs: Investigate how to document per-component design tokens

### ISSUE THREAD

**Issue by bddjong** [Gemeente-DenHaag/denhaag-component-library#198]
Documentation in storybook should contain a section describing the available design tokens for each component. This will probably need to be done through a .mdx file. We need to investigate how to document them.

Ideally, the design tokens for each component can be found on it's relevant docs page in storybook. The design token plugin which we're currently using has a Design Token block which can be used in MDX. That might be a good solution.

**Acceptance criteria**
- [x] Conclusion on how to document design tokens in storybook
- [x] Solution reviewed by NLDS 
- [x] Example implemented for button component

**Comment by GewoonMaarten** [comment]
While you can import existing code in MDX, you cannot import existing story as we have them right now. The stories that we created are implemented with `@storybook/react`. But in MDX they should be created with `@storybook/addon-docs/blocks`. 

This code:
```tsx
/* Button.stories.mdx */
import { Meta, Canvas } from "@storybook/addon-docs/blocks";
import { PrimaryAction } from "./Button.stories";
import { Button } from ".";

<Meta title="MDX/Button" component={Button} />

<Canvas>
  <PrimaryAction />
</Canvas>
```
Results in this story:
![image](https://user-images.githubusercontent.com/10438686/122193089-7e0a0680-ce94-11eb-9f4f-5015b270ed5a.png)

As far as I'm aware, you can also not use Typescript or JavaScript in MDX. They should be in separate files, which can then be imported.

If we want to display the design tokens we first need to import all design tokens, instead of only the general ones. We then need to annotate with a name and presenter:
```css
/* tokens-button.css */
:root {
  /**
  * @tokens Button
  * @presenter Button
  */
  --denhaag-button-border-radius: var(--denhaag-border-radius);
  --denhaag-button-border-width: 1px;
  /* ... */
  --denhaag-button-large-size-padding-block: 10px;
  --denhaag-button-large-size-padding-inline: 20px;
}
```
We can then use this in our story:
```tsx
/* button.stories.mdx */
import { DesignTokenDocBlock } from 'storybook-design-token/dist/doc-blocks';
<DesignTokenDocBlock categoryName="Button" viewType="table" />;
```
